//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Navigation_View.services_911consumidor_com {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="COCOServiceSoap", Namespace="http://services.911consumidor.com")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseDTO))]
    public partial class COCOService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public COCOService() {
            this.Url = "http://services.911consumidor.com/cocoservice.asmx";
        }
        
        public COCOService(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.911consumidor.com/GetActivePublications", RequestNamespace="http://services.911consumidor.com", ResponseNamespace="http://services.911consumidor.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PublicationDTO[] GetActivePublications(string key) {
            object[] results = this.Invoke("GetActivePublications", new object[] {
                        key});
            return ((PublicationDTO[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetActivePublications(string key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetActivePublications", new object[] {
                        key}, callback, asyncState);
        }
        
        /// <remarks/>
        public PublicationDTO[] EndGetActivePublications(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PublicationDTO[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.911consumidor.com/CreateTicket", RequestNamespace="http://services.911consumidor.com", ResponseNamespace="http://services.911consumidor.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateTicket(TicketDTO objDto, string key) {
            object[] results = this.Invoke("CreateTicket", new object[] {
                        objDto,
                        key});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateTicket(TicketDTO objDto, string key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateTicket", new object[] {
                        objDto,
                        key}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndCreateTicket(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.911consumidor.com/CreateTicketDetail", RequestNamespace="http://services.911consumidor.com", ResponseNamespace="http://services.911consumidor.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateTicketDetail(TicketDetailDTO objDto, string key) {
            object[] results = this.Invoke("CreateTicketDetail", new object[] {
                        objDto,
                        key});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateTicketDetail(TicketDetailDTO objDto, string key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateTicketDetail", new object[] {
                        objDto,
                        key}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndCreateTicketDetail(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.911consumidor.com/GetTicketsByUser", RequestNamespace="http://services.911consumidor.com", ResponseNamespace="http://services.911consumidor.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TicketDTO[] GetTicketsByUser(string clientID, string key) {
            object[] results = this.Invoke("GetTicketsByUser", new object[] {
                        clientID,
                        key});
            return ((TicketDTO[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTicketsByUser(string clientID, string key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTicketsByUser", new object[] {
                        clientID,
                        key}, callback, asyncState);
        }
        
        /// <remarks/>
        public TicketDTO[] EndGetTicketsByUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TicketDTO[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.911consumidor.com/AccountRegistration", RequestNamespace="http://services.911consumidor.com", ResponseNamespace="http://services.911consumidor.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserDTO AccountRegistration(UserDTO objDto, string key) {
            object[] results = this.Invoke("AccountRegistration", new object[] {
                        objDto,
                        key});
            return ((UserDTO)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAccountRegistration(UserDTO objDto, string key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AccountRegistration", new object[] {
                        objDto,
                        key}, callback, asyncState);
        }
        
        /// <remarks/>
        public UserDTO EndAccountRegistration(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UserDTO)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.911consumidor.com/AccountLogin", RequestNamespace="http://services.911consumidor.com", ResponseNamespace="http://services.911consumidor.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserDTO AccountLogin(UserDTO objDto, string key) {
            object[] results = this.Invoke("AccountLogin", new object[] {
                        objDto,
                        key});
            return ((UserDTO)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAccountLogin(UserDTO objDto, string key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AccountLogin", new object[] {
                        objDto,
                        key}, callback, asyncState);
        }
        
        /// <remarks/>
        public UserDTO EndAccountLogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UserDTO)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.911consumidor.com")]
    public partial class PublicationDTO : BaseDTO {
        
        /// <remarks/>
        public string Tittle;
        
        /// <remarks/>
        public string SubTittle;
        
        /// <remarks/>
        public string Content;
        
        /// <remarks/>
        public System.DateTime PublicationDate;
        
        /// <remarks/>
        public StatusDTO Status;
        
        /// <remarks/>
        public TypeDTO Type;
        
        /// <remarks/>
        public UserDTO User;
        
        /// <remarks/>
        public System.DateTime CreationDate;
        
        /// <remarks/>
        public string ImageUrl;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.911consumidor.com")]
    public partial class StatusDTO : BaseDTO {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Desc;
        
        /// <remarks/>
        public int OBJ_ID;
        
        /// <remarks/>
        public ObjectDTO Object;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.911consumidor.com")]
    public partial class ObjectDTO : BaseDTO {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Desc;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TicketDetailDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TicketDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TypeDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PublicationDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.911consumidor.com")]
    public abstract partial class BaseDTO {
        
        /// <remarks/>
        public int Id;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.911consumidor.com")]
    public partial class TicketDetailDTO : BaseDTO {
        
        /// <remarks/>
        public int TIC_ID;
        
        /// <remarks/>
        public System.DateTime DetailDate;
        
        /// <remarks/>
        public string Message;
        
        /// <remarks/>
        public StatusDTO Status;
        
        /// <remarks/>
        public UserDTO Agent;
        
        /// <remarks/>
        public string Subject;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.911consumidor.com")]
    public partial class UserDTO : BaseDTO {
        
        /// <remarks/>
        public string UserId;
        
        /// <remarks/>
        public string FirstName;
        
        /// <remarks/>
        public string LastName;
        
        /// <remarks/>
        public string Email;
        
        /// <remarks/>
        public string Phone;
        
        /// <remarks/>
        public string AddressState;
        
        /// <remarks/>
        public string AddressCity;
        
        /// <remarks/>
        public string PostalCode;
        
        /// <remarks/>
        public string Password;
        
        /// <remarks/>
        public string Device;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.911consumidor.com")]
    public partial class TicketDTO : BaseDTO {
        
        /// <remarks/>
        public System.DateTime TicketDate;
        
        /// <remarks/>
        public StatusDTO Status;
        
        /// <remarks/>
        public TypeDTO Type;
        
        /// <remarks/>
        public UserDTO User;
        
        /// <remarks/>
        public UserDTO Client;
        
        /// <remarks/>
        public string Notes;
        
        /// <remarks/>
        public TicketDetailDTO[] TicketDetail;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.911consumidor.com")]
    public partial class TypeDTO : BaseDTO {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Desc;
        
        /// <remarks/>
        public ObjectDTO Object;
        
        /// <remarks/>
        public int ObjId;
    }
}
